"""
    All the data/patterns to exclude when mapping.
    Modify as needed to remove tables and columns with unmappable entities.
"""

exclude_table_prefixes = ('pr_', 'temp_', 'ti_') # pr is production, temp is temporary, ti is still being crawled (ingested)

exclude_tables = (
    'l2_nif_0000_00508_data_gene',
    'l2_nif_0000_00508_data_gene_expression',
)

exclude_columns = {  # TODO cull these using the column mappings
                  'l2_nlx_151885_data_ephys':(
                      'id',
                      'e_uid',
                      'nelx_id',
                  ),
                  'l2_nlx_151885_data_neuron':(
                      'id',
                      'e_uid',
                      'nelx_id',
                  ),
                  'l2_nlx_151885_data_summary':(
                      'e_uid',
                      'id',
                      'num_nedms',
                      'value_sd',
                      'num_articles',
                      'n_id',
                      'e_id',
                      'value_mean',
                      'nelx_id',
                  ),
                  'l2_nif_0000_00006_data_nif_neuron':(
                      'volume',
                      'url_reference',
                      'surface',
                      'soma_surface',
                      'png_url',
                      'min_age',
                      'max_age',
                      'min_weight',
                      'max_weight',  # TODO UNITS! probably @ column level
                      'neuron_id',
                      'e_uid',
                      'neuron_name',  # these are the experimenter supplied 'names' ie exp local identifiers
                      'note',  # TODO these may contain some useful methods data...
                  ),
                  'l2_nif_0000_00006_data_neuron_article':(
                      'e_uid',
                      'neuron_id',
                      'ocdate',
                      'article_id',
                      'pmid',
                  ),
                  'l2_nif_0000_00006_data_allpublications':(
                      'e_uid',
                      'doi',
                      'paper_id',
                      'pmid',
                      'year',
                      'article_id',
                      'ocdate',
                      'paper_title',  # TODO tagging withing using 'mentions' ????
                      'related_page',
                      'first_author',  # TODO ORCID/neurotree mapping???
                      'last_author',  # TODO ORCID/neurotree
                      'journal',  # TODO who tracks these fellows?
                      'no_of_reconstructions',
                  ),
                  'l2_nif_0000_37639_image_imageannotation':(
                      'e_uid',
                      'id',
                      'entry_value',
                      'entry_ns',
                  ),
                  'l2_nif_0000_37639_image_imagedetail':(
                      'e_uid',
                      'id',
                      'xml',
                      'attribution',
                      'file_size',
                      'group_name',
                      'relative_file_path',
                      'imagedescription',  # TODO tagging inside?
                      'name',  # this is the file name
                  ),
                  'l2_nif_0000_37639_onto_label':(
                      'onto_id',  # FIXME map this

                  ),
                  'l2_nif_0000_00508_specimen_donor':(
                      #'age_id',  # we DO need to map this ;_; BUT HOW
                      'e_uid',
                      'external_donor_name',  # do need to map :/
                      'id',
                      'name',  # XXX there are two additional annotations that I cannot figure out in these: IVSCC and GSL
                      'specimen_id',
                      'tags',  # compound again
                  ),
                  'l2_nif_0000_00508_specimen_ephys_feature':(
                      'adaptation',
                      'avg_isi',
                      'blowout_voltage',
                      'e_uid',
                      'electrode_0_pa',
                      'f_i_curve_slope',
                      'fast_trough_t_long_square',
                      'fast_trough_t_ramp',
                      'fast_trough_t_short_square',
                      'fast_trough_v_long_square',
                      'fast_trough_v_ramp',
                      'fast_trough_v_short_square',
                      'id',
                      'initial_access_resistance',
                      'input_resistance_mohm',
                      'latency',
                      'peak_t_long_square',
                      'peak_t_ramp',
                      'peak_t_short_square',
                      'peak_v_long_square',
                      'peak_v_ramp',
                      'peak_v_short_square',
                      'rheobase_sweep_id',
                      'ri',
                      'sag',
                      'seal_gohm',
                      'slow_trough_t_long_square',
                      'slow_trough_t_ramp',
                      'slow_trough_t_short_square',
                      'slow_trough_v_long_square',
                      'slow_trough_v_ramp',
                      'slow_trough_v_short_square',
                      'specimen_id',
                      'tau',
                      'threshold_i_long_square',
                      'threshold_i_ramp',
                      'threshold_i_short_square',
                      'threshold_t_long_square',
                      'threshold_t_ramp',
                      'threshold_t_short_square',
                      'threshold_v_long_square',
                      'threshold_v_ramp',
                      'threshold_v_short_square',
                      'thumbnail_sweep_id',
                      'trough_t_long_square',
                      'trough_t_ramp',
                      'trough_t_short_square',
                      'trough_v_long_square',
                      'trough_v_ramp',
                      'trough_v_short_square',
                      'upstroke_downstroke_ratio_long_square',
                      'upstroke_downstroke_ratio_ramp',
                      'upstroke_downstroke_ratio_short_square',
                      'vm_for_sag',
                      'vrest',
                  ),  # I need to do the column mapping here!  (freeking er)
                  'l2_nif_0000_00508_specimen_neuron_reconstruction':(
                      'average_bifurcation_angle_local',
                      'average_bifurcation_angle_remote',
                      'average_contraction',
                      'average_diameter',
                      'average_fragmentation',
                      'average_parent_daughter_ratio',
                      'e_uid',
                      'hausdorff_dimension',
                      'id',
                      'max_branch_order',
                      'max_euclidean_distance',
                      'max_path_distance',
                      'number_bifurcations',
                      'number_branches',
                      'number_nodes',
                      'number_stems',
                      'number_tips',
                      'overall_depth',
                      'overall_height',
                      'overall_width',
                      'scale_factor_x',
                      'scale_factor_y',
                      'scale_factor_z',
                      'soma_surface',
                      'specimen_id',
                      #'tags',
                      'total_length',
                      'total_surface',
                      'total_volume',
                  ),
                  'l2_nif_0000_00508_specimen_specimen_tag':(
                      'ar_association_key_name',
                      'e_uid',
                      'id',
                      #'name',
                      'specimen_id',
                  ),
                  'l2_nif_0000_00508_specimen_structure':(
                      #'acronym',
                      'atlas_id',
                      'color_hex_triplet',
                      'depth',
                      'e_uid',
                      #'failed',  # need to know what this actually means
                      'failed_facet',
                      'graph_id',
                      'graph_order',
                      'hemisphere_id',
                      'id',
                      #'name',
                      'ontology_id',
                      'parent_structure_id',
                      #'safe_name',
                      'specimen_id',
                      'sphinx_id',
                      'structure_id_path',
                      'structure_name_facet',
                      'weight',
                  ),
                  'l2_nif_0000_00508_specimen_summary':(
                      'donor_id',
                      'e_uid',
                      'ephys_result_id',
                      'failed_facet',
                      #'hemisphere',  # this needs to be mapped
                      'id',
                      'is_cell_specimen',
                      'is_ish',
                      'name',  # same issue as w/ donor, IVSCC and GSL are a mystery
                      'parent_id',
                      'parent_x_coord',
                      'parent_y_coord',
                      'parent_z_coord',
                      'specimen_id_path',
                      'sphinx_id',
                      'structure_id',
                      'weight',
                  ),
                  'l2_nif_0000_00508_specimen_transgenic_line':(
                      'ar_association_key_name',
                      'description',
                      'donor_id',
                      'e_uid',
                      'id',
                      #'name',
                      #'originating_lab',
                      'specimen_id',
                      'stock_number',
                      'sub_image_annotation_id',
                      #'transgenic_line_source_name',
                      #'transgenic_line_type_code',
                      #'transgenic_line_type_name',
                      'url_prefix',
                      'url_suffix',
                  ),
                  'nlx_154697_8':(
                      'e_uid',
                      'link',
                      'notes',
                      'pmid',
                      'reference',
                      'ref_link',
                      'species_id',
                      'v_uid',
                      'v_uuid',
                      'v_lastmodified',
                  ),

                  #'relative_file_path',  # nasty one in??
                  #'id',
                  #'id1',
                  #'v_uid',
                  #'v_uuid',
                  #'pmid',
                  #'doi',
                  #'url',
                  #'url_reference',
                 }

